"use client"
import { Outfit } from "next/font/google";
import "./globals.css";
import Header from "./_components/Header";
import { useState } from "react";
import { Toaster } from "@/components/ui/sonner"
import { usePathname } from "next/navigation";
import { UpdateCartContext } from "./_context/UpdateCartContext";

const outfit = Outfit({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };



export default function RootLayout({ children }) {
  const params = usePathname()
  const [updateCart, setupdateCart] = useState(false)
  const showHeader= params=='/sign-in' || params=='/create-account'?false:true;
  return (
    <html lang="en">
      
      <body className={outfit.className}>
    <UpdateCartContext.Provider value={{updateCart, setupdateCart}}>
     {showHeader&& <Header/> }
        {children}
        <Toaster />
        </UpdateCartContext.Provider>
        </body>
    </html>
  );
}
